# Generated by Django 3.2.8 on 2021-12-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
    ]
